declare class Window {
    public titlebar: boolean;
    public visible: boolean;
    public sizable: boolean;
    public closable: boolean;
    public maximizable: boolean;
    public minimizable: boolean;
    public maximized: boolean;
    public minimized: boolean;
    public topmost: boolean;
    public pixelratio: number;
    public size: Vec2;
    public title: string;
    public view: View;
    public center(): void;
    public on(event: 'show', listener: () => void): void;
    public on(event: 'hide', listener: () => void): void;
    public on(event: 'close', listener: () => void): void;
    public on(event: 'resize', listener: () => void): void;
    public on(event: 'maximize', listener: () => void): void;
    public on(event: 'minimize', listener: () => void): void;
    public on(event: 'demaximize', listener: () => void): void;
    public on(event: 'deminimize', listener: () => void): void;
    public on(event: 'pixelratio', listener: () => void): void;
    public off(event: 'show', listener: () => void): void;
    public off(event: 'hide', listener: () => void): void;
    public off(event: 'close', listener: () => void): void;
    public off(event: 'resize', listener: () => void): void;
    public off(event: 'maximize', listener: () => void): void;
    public off(event: 'minimize', listener: () => void): void;
    public off(event: 'demaximize', listener: () => void): void;
    public off(event: 'deminimize', listener: () => void): void;
    public off(event: 'pixelratio', listener: () => void): void;
}