#pragma once

#include <Boom/Memory.hpp>
#include <Boom/Error.hpp>
#include <Boom/Math.hpp>
#include <Boom/Sleep.hpp>
#include <Boom/Time.hpp>
#include <Boom/Emitter.hpp>
#include <Boom/Input.hpp>
#include <Boom/OpenGL.hpp>
#include <Boom/Surface.hpp>
#include <Boom/Paint.hpp>
#include <Boom/App.hpp>
#include <Boom/Menu.hpp>
#include <Boom/Alert.hpp>
#include <Boom/Window.hpp>
#include <Boom/Image.hpp>
#include <Boom/Color.hpp>
#include <Boom/Brush.hpp>
#include <Boom/Node.hpp>
#include <Boom/File.hpp>
#include <Boom/Font.hpp>
#include <Boom/Text.hpp>
#include <Boom/Utilities.hpp>
