#include <cinttypes>

struct GLContextOptions {
    std::int32_t majorVersion;
    std::int32_t minorVersion;
    void* window;
};

struct GLContext;
struct GLSync;

using GLvoid = void;
using GLenum = std::uint32_t;
using GLboolean = std::uint8_t;
using GLbitfield = std::uint32_t;
using GLbyte = std::int32_t;
using GLubyte = std::uint8_t;
using GLshort = std::int16_t;
using GLushort = std::uint16_t;
using GLint = std::int32_t;
using GLuint = std::uint32_t;
using GLclampx = std::int32_t;
using GLsizei = std::int32_t;
using GLfloat = float;
using GLclampf = float;
using GLdouble = double;
using GLclampd = double;
using GLeglClientBufferEXT = void*;
using GLeglImageOES = void*;
using GLchar = char;
using GLcharARB = char;
using GLhalf = std::uint16_t;
using GLhalfARB = std::uint16_t;
using GLfixed = std::int32_t;
using GLintptr = std::intptr_t;
using GLintptrARB = std::intptr_t;
using GLsizeiptr = std::int64_t;
using GLsizeiptrARB = std::int64_t;
using GLint64 = std::int64_t;
using GLint64EXT = std::int64_t;
using GLuint64 = std::uint64_t;
using GLuint64EXT = std::uint64_t;
using GLDebugProc = void(*)(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar* message, const void* userParam);
using GLCullFace = void(*)(GLenum mode);
using GLFrontFace = void(*)(GLenum mode);
using GLHint = void(*)(GLenum target, GLenum mode);
using GLLineWidth = void(*)(GLfloat width);
using GLPointSize = void(*)(GLfloat size);
using GLPolygonMode = void(*)(GLenum face, GLenum mode);
using GLScissor = void(*)(GLint x, GLint y, GLsizei width, GLsizei height);
using GLTexParameterf = void(*)(GLenum target, GLenum pname, GLfloat param);
using GLTexParameterfv = void(*)(GLenum target, GLenum pname, const GLfloat *params);
using GLTexParameteri = void(*)(GLenum target, GLenum pname, GLint param);
using GLTexParameteriv = void(*)(GLenum target, GLenum pname, const GLint *params);
using GLTexImage1D = void(*)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const void *pixels);
using GLTexImage2D = void(*)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels);
using GLDrawBuffer = void(*)(GLenum buf);
using GLClear = void(*)(GLbitfield mask);
using GLClearColor = void(*)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
using GLClearStencil = void(*)(GLint s);
using GLClearDepth = void(*)(GLdouble depth);
using GLStencilMask = void(*)(GLuint mask);
using GLColorMask = void(*)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
using GLDepthMask = void(*)(GLboolean flag);
using GLDisable = void(*)(GLenum cap);
using GLEnable = void(*)(GLenum cap);
using GLFinish = void(*)(void);
using GLFlush = void(*)(void);
using GLBlendFunc = void(*)(GLenum sfactor, GLenum dfactor);
using GLLogicOp = void(*)(GLenum opcode);
using GLStencilFunc = void(*)(GLenum func, GLint ref, GLuint mask);
using GLStencilOp = void(*)(GLenum fail, GLenum zfail, GLenum zpass);
using GLDepthFunc = void(*)(GLenum func);
using GLPixelStoref = void(*)(GLenum pname, GLfloat param);
using GLPixelStorei = void(*)(GLenum pname, GLint param);
using GLReadBuffer = void(*)(GLenum src);
using GLReadPixels = void(*)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
using GLGetBooleanv = void(*)(GLenum pname, GLboolean *data);
using GLGetDoublev = void(*)(GLenum pname, GLdouble *data);
using GLGetFloatv = void(*)(GLenum pname, GLfloat *data);
using GLGetIntegerv = void(*)(GLenum pname, GLint *data);
using GLGetTexImage = void(*)(GLenum target, GLint level, GLenum format, GLenum type, void *pixels);
using GLGetTexParameterfv = void(*)(GLenum target, GLenum pname, GLfloat *params);
using GLGetTexParameteriv = void(*)(GLenum target, GLenum pname, GLint *params);
using GLGetTexLevelParameterfv = void(*)(GLenum target, GLint level, GLenum pname, GLfloat *params);
using GLGetTexLevelParameteriv = void(*)(GLenum target, GLint level, GLenum pname, GLint *params);
using GLDepthRange = void(*)(GLdouble n, GLdouble f);
using GLViewport = void(*)(GLint x, GLint y, GLsizei width, GLsizei height);
using GLDrawArrays = void(*)(GLenum mode, GLint first, GLsizei count);
using GLDrawElements = void(*)(GLenum mode, GLsizei count, GLenum type, const void *indices);
using GLPolygonOffset = void(*)(GLfloat factor, GLfloat units);
using GLCopyTexImage1D = void(*)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border);
using GLCopyTexImage2D = void(*)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
using GLCopyTexSubImage1D = void(*)(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
using GLCopyTexSubImage2D = void(*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
using GLTexSubImage1D = void(*)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels);
using GLTexSubImage2D = void(*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
using GLBindTexture = void(*)(GLenum target, GLuint texture);
using GLDeleteTextures = void(*)(GLsizei n, const GLuint *textures);
using GLGenTextures = void(*)(GLsizei n, GLuint *textures);
using GLDrawRangeElements = void(*)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices);
using GLTexImage3D = void(*)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels);
using GLTexSubImage3D = void(*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
using GLCopyTexSubImage3D = void(*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
using GLActiveTexture = void(*)(GLenum texture);
using GLSampleCoverage = void(*)(GLfloat value, GLboolean invert);
using GLCompressedTexImage3D = void(*)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data);
using GLCompressedTexImage2D = void(*)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data);
using GLCompressedTexImage1D = void(*)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const void *data);
using GLCompressedTexSubImage3D = void(*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data);
using GLCompressedTexSubImage2D = void(*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
using GLCompressedTexSubImage1D = void(*)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data);
using GLGetCompressedTexImage = void(*)(GLenum target, GLint level, void *img);
using GLBlendFuncSeparate = void(*)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
using GLMultiDrawArrays = void(*)(GLenum mode, const GLint *first, const GLsizei *count, GLsizei drawcount);
using GLMultiDrawElements = void(*)(GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount);
using GLPointParameterf = void(*)(GLenum pname, GLfloat param);
using GLPointParameterfv = void(*)(GLenum pname, const GLfloat *params);
using GLPointParameteri = void(*)(GLenum pname, GLint param);
using GLPointParameteriv = void(*)(GLenum pname, const GLint *params);
using GLBlendColor = void(*)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
using GLBlendEquation = void(*)(GLenum mode);
using GLGenQueries = void(*)(GLsizei n, GLuint *ids);
using GLDeleteQueries = void(*)(GLsizei n, const GLuint *ids);
using GLBeginQuery = void(*)(GLenum target, GLuint id);
using GLEndQuery = void(*)(GLenum target);
using GLGetQueryiv = void(*)(GLenum target, GLenum pname, GLint *params);
using GLGetQueryObjectiv = void(*)(GLuint id, GLenum pname, GLint *params);
using GLGetQueryObjectuiv = void(*)(GLuint id, GLenum pname, GLuint *params);
using GLBindBuffer = void(*)(GLenum target, GLuint buffer);
using GLDeleteBuffers = void(*)(GLsizei n, const GLuint *buffers);
using GLGenBuffers = void(*)(GLsizei n, GLuint *buffers);
using GLBufferData = void(*)(GLenum target, GLsizeiptr size, const void *data, GLenum usage);
using GLBufferSubData = void(*)(GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
using GLGetBufferSubData = void(*)(GLenum target, GLintptr offset, GLsizeiptr size, void *data);
using GLGetBufferParameteriv = void(*)(GLenum target, GLenum pname, GLint *params);
using GLGetBufferPointerv = void(*)(GLenum target, GLenum pname, void **params);
using GLBlendEquationSeparate = void(*)(GLenum modeRGB, GLenum modeAlpha);
using GLDrawBuffers = void(*)(GLsizei n, const GLenum *bufs);
using GLStencilOpSeparate = void(*)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
using GLStencilFuncSeparate = void(*)(GLenum face, GLenum func, GLint ref, GLuint mask);
using GLStencilMaskSeparate = void(*)(GLenum face, GLuint mask);
using GLAttachShader = void(*)(GLuint program, GLuint shader);
using GLBindAttribLocation = void(*)(GLuint program, GLuint index, const GLchar *name);
using GLCompileShader = void(*)(GLuint shader);
using GLDeleteProgram = void(*)(GLuint program);
using GLDeleteShader = void(*)(GLuint shader);
using GLDetachShader = void(*)(GLuint program, GLuint shader);
using GLDisableVertexAttribArray = void(*)(GLuint index);
using GLEnableVertexAttribArray = void(*)(GLuint index);
using GLGetActiveAttrib = void(*)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
using GLGetActiveUniform = void(*)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
using GLGetAttachedShaders = void(*)(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders);
using GLGetProgramiv = void(*)(GLuint program, GLenum pname, GLint *params);
using GLGetProgramInfoLog = void(*)(GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
using GLGetShaderiv = void(*)(GLuint shader, GLenum pname, GLint *params);
using GLGetShaderInfoLog = void(*)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
using GLGetShaderSource = void(*)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
using GLGetUniformfv = void(*)(GLuint program, GLint location, GLfloat *params);
using GLGetUniformiv = void(*)(GLuint program, GLint location, GLint *params);
using GLGetVertexAttribdv = void(*)(GLuint index, GLenum pname, GLdouble *params);
using GLGetVertexAttribfv = void(*)(GLuint index, GLenum pname, GLfloat *params);
using GLGetVertexAttribiv = void(*)(GLuint index, GLenum pname, GLint *params);
using GLGetVertexAttribPointerv = void(*)(GLuint index, GLenum pname, void **pointer);
using GLLinkProgram = void(*)(GLuint program);
using GLShaderSource = void(*)(GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length);
using GLUseProgram = void(*)(GLuint program);
using GLUniform1f = void(*)(GLint location, GLfloat v0);
using GLUniform2f = void(*)(GLint location, GLfloat v0, GLfloat v1);
using GLUniform3f = void(*)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
using GLUniform4f = void(*)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
using GLUniform1i = void(*)(GLint location, GLint v0);
using GLUniform2i = void(*)(GLint location, GLint v0, GLint v1);
using GLUniform3i = void(*)(GLint location, GLint v0, GLint v1, GLint v2);
using GLUniform4i = void(*)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
using GLUniform1fv = void(*)(GLint location, GLsizei count, const GLfloat *value);
using GLUniform2fv = void(*)(GLint location, GLsizei count, const GLfloat *value);
using GLUniform3fv = void(*)(GLint location, GLsizei count, const GLfloat *value);
using GLUniform4fv = void(*)(GLint location, GLsizei count, const GLfloat *value);
using GLUniform1iv = void(*)(GLint location, GLsizei count, const GLint *value);
using GLUniform2iv = void(*)(GLint location, GLsizei count, const GLint *value);
using GLUniform3iv = void(*)(GLint location, GLsizei count, const GLint *value);
using GLUniform4iv = void(*)(GLint location, GLsizei count, const GLint *value);
using GLUniformMatrix2fv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLUniformMatrix3fv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLUniformMatrix4fv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLValidateProgram = void(*)(GLuint program);
using GLVertexAttrib1d = void(*)(GLuint index, GLdouble x);
using GLVertexAttrib1dv = void(*)(GLuint index, const GLdouble *v);
using GLVertexAttrib1f = void(*)(GLuint index, GLfloat x);
using GLVertexAttrib1fv = void(*)(GLuint index, const GLfloat *v);
using GLVertexAttrib1s = void(*)(GLuint index, GLshort x);
using GLVertexAttrib1sv = void(*)(GLuint index, const GLshort *v);
using GLVertexAttrib2d = void(*)(GLuint index, GLdouble x, GLdouble y);
using GLVertexAttrib2dv = void(*)(GLuint index, const GLdouble *v);
using GLVertexAttrib2f = void(*)(GLuint index, GLfloat x, GLfloat y);
using GLVertexAttrib2fv = void(*)(GLuint index, const GLfloat *v);
using GLVertexAttrib2s = void(*)(GLuint index, GLshort x, GLshort y);
using GLVertexAttrib2sv = void(*)(GLuint index, const GLshort *v);
using GLVertexAttrib3d = void(*)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
using GLVertexAttrib3dv = void(*)(GLuint index, const GLdouble *v);
using GLVertexAttrib3f = void(*)(GLuint index, GLfloat x, GLfloat y, GLfloat z);
using GLVertexAttrib3fv = void(*)(GLuint index, const GLfloat *v);
using GLVertexAttrib3s = void(*)(GLuint index, GLshort x, GLshort y, GLshort z);
using GLVertexAttrib3sv = void(*)(GLuint index, const GLshort *v);
using GLVertexAttrib4Nbv = void(*)(GLuint index, const GLbyte *v);
using GLVertexAttrib4Niv = void(*)(GLuint index, const GLint *v);
using GLVertexAttrib4Nsv = void(*)(GLuint index, const GLshort *v);
using GLVertexAttrib4Nub = void(*)(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w);
using GLVertexAttrib4Nubv = void(*)(GLuint index, const GLubyte *v);
using GLVertexAttrib4Nuiv = void(*)(GLuint index, const GLuint *v);
using GLVertexAttrib4Nusv = void(*)(GLuint index, const GLushort *v);
using GLVertexAttrib4bv = void(*)(GLuint index, const GLbyte *v);
using GLVertexAttrib4d = void(*)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
using GLVertexAttrib4dv = void(*)(GLuint index, const GLdouble *v);
using GLVertexAttrib4f = void(*)(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
using GLVertexAttrib4fv = void(*)(GLuint index, const GLfloat *v);
using GLVertexAttrib4iv = void(*)(GLuint index, const GLint *v);
using GLVertexAttrib4s = void(*)(GLuint index, GLshort x, GLshort y, GLshort z, GLshort w);
using GLVertexAttrib4sv = void(*)(GLuint index, const GLshort *v);
using GLVertexAttrib4ubv = void(*)(GLuint index, const GLubyte *v);
using GLVertexAttrib4uiv = void(*)(GLuint index, const GLuint *v);
using GLVertexAttrib4usv = void(*)(GLuint index, const GLushort *v);
using GLVertexAttribPointer = void(*)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
using GLUniformMatrix2x3fv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLUniformMatrix3x2fv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLUniformMatrix2x4fv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLUniformMatrix4x2fv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLUniformMatrix3x4fv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLUniformMatrix4x3fv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLColorMaski = void(*)(GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
using GLGetBooleani_v = void(*)(GLenum target, GLuint index, GLboolean *data);
using GLGetIntegeri_v = void(*)(GLenum target, GLuint index, GLint *data);
using GLEnablei = void(*)(GLenum target, GLuint index);
using GLDisablei = void(*)(GLenum target, GLuint index);
using GLBeginTransformFeedback = void(*)(GLenum primitiveMode);
using GLEndTransformFeedback = void(*)(void);
using GLBindBufferRange = void(*)(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
using GLBindBufferBase = void(*)(GLenum target, GLuint index, GLuint buffer);
using GLTransformFeedbackVaryings = void(*)(GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode);
using GLGetTransformFeedbackVarying = void(*)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name);
using GLClampColor = void(*)(GLenum target, GLenum clamp);
using GLBeginConditionalRender = void(*)(GLuint id, GLenum mode);
using GLEndConditionalRender = void(*)(void);
using GLVertexAttribIPointer = void(*)(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
using GLGetVertexAttribIiv = void(*)(GLuint index, GLenum pname, GLint *params);
using GLGetVertexAttribIuiv = void(*)(GLuint index, GLenum pname, GLuint *params);
using GLVertexAttribI1i = void(*)(GLuint index, GLint x);
using GLVertexAttribI2i = void(*)(GLuint index, GLint x, GLint y);
using GLVertexAttribI3i = void(*)(GLuint index, GLint x, GLint y, GLint z);
using GLVertexAttribI4i = void(*)(GLuint index, GLint x, GLint y, GLint z, GLint w);
using GLVertexAttribI1ui = void(*)(GLuint index, GLuint x);
using GLVertexAttribI2ui = void(*)(GLuint index, GLuint x, GLuint y);
using GLVertexAttribI3ui = void(*)(GLuint index, GLuint x, GLuint y, GLuint z);
using GLVertexAttribI4ui = void(*)(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
using GLVertexAttribI1iv = void(*)(GLuint index, const GLint *v);
using GLVertexAttribI2iv = void(*)(GLuint index, const GLint *v);
using GLVertexAttribI3iv = void(*)(GLuint index, const GLint *v);
using GLVertexAttribI4iv = void(*)(GLuint index, const GLint *v);
using GLVertexAttribI1uiv = void(*)(GLuint index, const GLuint *v);
using GLVertexAttribI2uiv = void(*)(GLuint index, const GLuint *v);
using GLVertexAttribI3uiv = void(*)(GLuint index, const GLuint *v);
using GLVertexAttribI4uiv = void(*)(GLuint index, const GLuint *v);
using GLVertexAttribI4bv = void(*)(GLuint index, const GLbyte *v);
using GLVertexAttribI4sv = void(*)(GLuint index, const GLshort *v);
using GLVertexAttribI4ubv = void(*)(GLuint index, const GLubyte *v);
using GLVertexAttribI4usv = void(*)(GLuint index, const GLushort *v);
using GLGetUniformuiv = void(*)(GLuint program, GLint location, GLuint *params);
using GLBindFragDataLocation = void(*)(GLuint program, GLuint color, const GLchar *name);
using GLUniform1ui = void(*)(GLint location, GLuint v0);
using GLUniform2ui = void(*)(GLint location, GLuint v0, GLuint v1);
using GLUniform3ui = void(*)(GLint location, GLuint v0, GLuint v1, GLuint v2);
using GLUniform4ui = void(*)(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
using GLUniform1uiv = void(*)(GLint location, GLsizei count, const GLuint *value);
using GLUniform2uiv = void(*)(GLint location, GLsizei count, const GLuint *value);
using GLUniform3uiv = void(*)(GLint location, GLsizei count, const GLuint *value);
using GLUniform4uiv = void(*)(GLint location, GLsizei count, const GLuint *value);
using GLTexParameterIiv = void(*)(GLenum target, GLenum pname, const GLint *params);
using GLTexParameterIuiv = void(*)(GLenum target, GLenum pname, const GLuint *params);
using GLGetTexParameterIiv = void(*)(GLenum target, GLenum pname, GLint *params);
using GLGetTexParameterIuiv = void(*)(GLenum target, GLenum pname, GLuint *params);
using GLClearBufferiv = void(*)(GLenum buffer, GLint drawbuffer, const GLint *value);
using GLClearBufferuiv = void(*)(GLenum buffer, GLint drawbuffer, const GLuint *value);
using GLClearBufferfv = void(*)(GLenum buffer, GLint drawbuffer, const GLfloat *value);
using GLClearBufferfi = void(*)(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
using GLBindRenderbuffer = void(*)(GLenum target, GLuint renderbuffer);
using GLDeleteRenderbuffers = void(*)(GLsizei n, const GLuint *renderbuffers);
using GLGenRenderbuffers = void(*)(GLsizei n, GLuint *renderbuffers);
using GLRenderbufferStorage = void(*)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
using GLGetRenderbufferParameteriv = void(*)(GLenum target, GLenum pname, GLint *params);
using GLBindFramebuffer = void(*)(GLenum target, GLuint framebuffer);
using GLDeleteFramebuffers = void(*)(GLsizei n, const GLuint *framebuffers);
using GLGenFramebuffers = void(*)(GLsizei n, GLuint *framebuffers);
using GLFramebufferTexture1D = void(*)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
using GLFramebufferTexture2D = void(*)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
using GLFramebufferTexture3D = void(*)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset);
using GLFramebufferRenderbuffer = void(*)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
using GLGetFramebufferAttachmentParameteriv = void(*)(GLenum target, GLenum attachment, GLenum pname, GLint *params);
using GLGenerateMipmap = void(*)(GLenum target);
using GLBlitFramebuffer = void(*)(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
using GLRenderbufferStorageMultisample = void(*)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
using GLFramebufferTextureLayer = void(*)(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
using GLFlushMappedBufferRange = void(*)(GLenum target, GLintptr offset, GLsizeiptr length);
using GLBindVertexArray = void(*)(GLuint array);
using GLDeleteVertexArrays = void(*)(GLsizei n, const GLuint *arrays);
using GLGenVertexArrays = void(*)(GLsizei n, GLuint *arrays);
using GLDrawArraysInstanced = void(*)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
using GLDrawElementsInstanced = void(*)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount);
using GLTexBuffer = void(*)(GLenum target, GLenum internalformat, GLuint buffer);
using GLPrimitiveRestartIndex = void(*)(GLuint index);
using GLCopyBufferSubData = void(*)(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
using GLGetUniformIndices = void(*)(GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices);
using GLGetActiveUniformsiv = void(*)(GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params);
using GLGetActiveUniformName = void(*)(GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformName);
using GLGetActiveUniformBlockiv = void(*)(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params);
using GLGetActiveUniformBlockName = void(*)(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName);
using GLUniformBlockBinding = void(*)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
using GLDrawElementsBaseVertex = void(*)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex);
using GLDrawRangeElementsBaseVertex = void(*)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices, GLint basevertex);
using GLDrawElementsInstancedBaseVertex = void(*)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex);
using GLMultiDrawElementsBaseVertex = void(*)(GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei drawcount, const GLint *basevertex);
using GLProvokingVertex = void(*)(GLenum mode);
using GLDeleteSync = void(*)(GLSync* sync);
using GLWaitSync = void(*)(GLSync* sync, GLbitfield flags, GLuint64 timeout);
using GLGetInteger64v = void(*)(GLenum pname, GLint64 *data);
using GLGetSynciv = void(*)(GLSync* sync, GLenum pname, GLsizei count, GLsizei *length, GLint *values);
using GLGetInteger64i_v = void(*)(GLenum target, GLuint index, GLint64 *data);
using GLGetBufferParameteri64v = void(*)(GLenum target, GLenum pname, GLint64 *params);
using GLFramebufferTexture = void(*)(GLenum target, GLenum attachment, GLuint texture, GLint level);
using GLTexImage2DMultisample = void(*)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
using GLTexImage3DMultisample = void(*)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
using GLGetMultisamplefv = void(*)(GLenum pname, GLuint index, GLfloat *val);
using GLSampleMaski = void(*)(GLuint maskNumber, GLbitfield mask);
using GLBindFragDataLocationIndexed = void(*)(GLuint program, GLuint colorNumber, GLuint index, const GLchar *name);
using GLGenSamplers = void(*)(GLsizei count, GLuint *samplers);
using GLDeleteSamplers = void(*)(GLsizei count, const GLuint *samplers);
using GLBindSampler = void(*)(GLuint unit, GLuint sampler);
using GLSamplerParameteri = void(*)(GLuint sampler, GLenum pname, GLint param);
using GLSamplerParameteriv = void(*)(GLuint sampler, GLenum pname, const GLint *param);
using GLSamplerParameterf = void(*)(GLuint sampler, GLenum pname, GLfloat param);
using GLSamplerParameterfv = void(*)(GLuint sampler, GLenum pname, const GLfloat *param);
using GLSamplerParameterIiv = void(*)(GLuint sampler, GLenum pname, const GLint *param);
using GLSamplerParameterIuiv = void(*)(GLuint sampler, GLenum pname, const GLuint *param);
using GLGetSamplerParameteriv = void(*)(GLuint sampler, GLenum pname, GLint *params);
using GLGetSamplerParameterIiv = void(*)(GLuint sampler, GLenum pname, GLint *params);
using GLGetSamplerParameterfv = void(*)(GLuint sampler, GLenum pname, GLfloat *params);
using GLGetSamplerParameterIuiv = void(*)(GLuint sampler, GLenum pname, GLuint *params);
using GLQueryCounter = void(*)(GLuint id, GLenum target);
using GLGetQueryObjecti64v = void(*)(GLuint id, GLenum pname, GLint64 *params);
using GLGetQueryObjectui64v = void(*)(GLuint id, GLenum pname, GLuint64 *params);
using GLVertexAttribDivisor = void(*)(GLuint index, GLuint divisor);
using GLVertexAttribP1ui = void(*)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
using GLVertexAttribP1uiv = void(*)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
using GLVertexAttribP2ui = void(*)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
using GLVertexAttribP2uiv = void(*)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
using GLVertexAttribP3ui = void(*)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
using GLVertexAttribP3uiv = void(*)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
using GLVertexAttribP4ui = void(*)(GLuint index, GLenum type, GLboolean normalized, GLuint value);
using GLVertexAttribP4uiv = void(*)(GLuint index, GLenum type, GLboolean normalized, const GLuint *value);
using GLVertexP2ui = void(*)(GLenum type, GLuint value);
using GLVertexP2uiv = void(*)(GLenum type, const GLuint *value);
using GLVertexP3ui = void(*)(GLenum type, GLuint value);
using GLVertexP3uiv = void(*)(GLenum type, const GLuint *value);
using GLVertexP4ui = void(*)(GLenum type, GLuint value);
using GLVertexP4uiv = void(*)(GLenum type, const GLuint *value);
using GLTexCoordP1ui = void(*)(GLenum type, GLuint coords);
using GLTexCoordP1uiv = void(*)(GLenum type, const GLuint *coords);
using GLTexCoordP2ui = void(*)(GLenum type, GLuint coords);
using GLTexCoordP2uiv = void(*)(GLenum type, const GLuint *coords);
using GLTexCoordP3ui = void(*)(GLenum type, GLuint coords);
using GLTexCoordP3uiv = void(*)(GLenum type, const GLuint *coords);
using GLTexCoordP4ui = void(*)(GLenum type, GLuint coords);
using GLTexCoordP4uiv = void(*)(GLenum type, const GLuint *coords);
using GLMultiTexCoordP1ui = void(*)(GLenum texture, GLenum type, GLuint coords);
using GLMultiTexCoordP1uiv = void(*)(GLenum texture, GLenum type, const GLuint *coords);
using GLMultiTexCoordP2ui = void(*)(GLenum texture, GLenum type, GLuint coords);
using GLMultiTexCoordP2uiv = void(*)(GLenum texture, GLenum type, const GLuint *coords);
using GLMultiTexCoordP3ui = void(*)(GLenum texture, GLenum type, GLuint coords);
using GLMultiTexCoordP3uiv = void(*)(GLenum texture, GLenum type, const GLuint *coords);
using GLMultiTexCoordP4ui = void(*)(GLenum texture, GLenum type, GLuint coords);
using GLMultiTexCoordP4uiv = void(*)(GLenum texture, GLenum type, const GLuint *coords);
using GLNormalP3ui = void(*)(GLenum type, GLuint coords);
using GLNormalP3uiv = void(*)(GLenum type, const GLuint *coords);
using GLColorP3ui = void(*)(GLenum type, GLuint color);
using GLColorP3uiv = void(*)(GLenum type, const GLuint *color);
using GLColorP4ui = void(*)(GLenum type, GLuint color);
using GLColorP4uiv = void(*)(GLenum type, const GLuint *color);
using GLSecondaryColorP3ui = void(*)(GLenum type, GLuint color);
using GLSecondaryColorP3uiv = void(*)(GLenum type, const GLuint *color);
using GLMinSampleShading = void(*)(GLfloat value);
using GLBlendEquationi = void(*)(GLuint buf, GLenum mode);
using GLBlendEquationSeparatei = void(*)(GLuint buf, GLenum modeRGB, GLenum modeAlpha);
using GLBlendFunci = void(*)(GLuint buf, GLenum src, GLenum dst);
using GLBlendFuncSeparatei = void(*)(GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
using GLDrawArraysIndirect = void(*)(GLenum mode, const void *indirect);
using GLDrawElementsIndirect = void(*)(GLenum mode, GLenum type, const void *indirect);
using GLUniform1d = void(*)(GLint location, GLdouble x);
using GLUniform2d = void(*)(GLint location, GLdouble x, GLdouble y);
using GLUniform3d = void(*)(GLint location, GLdouble x, GLdouble y, GLdouble z);
using GLUniform4d = void(*)(GLint location, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
using GLUniform1dv = void(*)(GLint location, GLsizei count, const GLdouble *value);
using GLUniform2dv = void(*)(GLint location, GLsizei count, const GLdouble *value);
using GLUniform3dv = void(*)(GLint location, GLsizei count, const GLdouble *value);
using GLUniform4dv = void(*)(GLint location, GLsizei count, const GLdouble *value);
using GLUniformMatrix2dv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLUniformMatrix3dv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLUniformMatrix4dv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLUniformMatrix2x3dv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLUniformMatrix2x4dv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLUniformMatrix3x2dv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLUniformMatrix3x4dv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLUniformMatrix4x2dv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLUniformMatrix4x3dv = void(*)(GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLGetUniformdv = void(*)(GLuint program, GLint location, GLdouble *params);
using GLGetActiveSubroutineUniformiv = void(*)(GLuint program, GLenum shadertype, GLuint index, GLenum pname, GLint *values);
using GLGetActiveSubroutineUniformName = void(*)(GLuint program, GLenum shadertype, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
using GLGetActiveSubroutineName = void(*)(GLuint program, GLenum shadertype, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
using GLUniformSubroutinesuiv = void(*)(GLenum shadertype, GLsizei count, const GLuint *indices);
using GLGetUniformSubroutineuiv = void(*)(GLenum shadertype, GLint location, GLuint *params);
using GLGetProgramStageiv = void(*)(GLuint program, GLenum shadertype, GLenum pname, GLint *values);
using GLPatchParameteri = void(*)(GLenum pname, GLint value);
using GLPatchParameterfv = void(*)(GLenum pname, const GLfloat *values);
using GLBindTransformFeedback = void(*)(GLenum target, GLuint id);
using GLDeleteTransformFeedbacks = void(*)(GLsizei n, const GLuint *ids);
using GLGenTransformFeedbacks = void(*)(GLsizei n, GLuint *ids);
using GLPauseTransformFeedback = void(*)(void);
using GLResumeTransformFeedback = void(*)(void);
using GLDrawTransformFeedback = void(*)(GLenum mode, GLuint id);
using GLDrawTransformFeedbackStream = void(*)(GLenum mode, GLuint id, GLuint stream);
using GLBeginQueryIndexed = void(*)(GLenum target, GLuint index, GLuint id);
using GLEndQueryIndexed = void(*)(GLenum target, GLuint index);
using GLGetQueryIndexediv = void(*)(GLenum target, GLuint index, GLenum pname, GLint *params);
using GLReleaseShaderCompiler = void(*)(void);
using GLShaderBinary = void(*)(GLsizei count, const GLuint *shaders, GLenum binaryFormat, const void *binary, GLsizei length);
using GLGetShaderPrecisionFormat = void(*)(GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision);
using GLDepthRangef = void(*)(GLfloat n, GLfloat f);
using GLClearDepthf = void(*)(GLfloat d);
using GLGetProgramBinary = void(*)(GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary);
using GLProgramBinary = void(*)(GLuint program, GLenum binaryFormat, const void *binary, GLsizei length);
using GLProgramParameteri = void(*)(GLuint program, GLenum pname, GLint value);
using GLUseProgramStages = void(*)(GLuint pipeline, GLbitfield stages, GLuint program);
using GLActiveShaderProgram = void(*)(GLuint pipeline, GLuint program);
using GLBindProgramPipeline = void(*)(GLuint pipeline);
using GLDeleteProgramPipelines = void(*)(GLsizei n, const GLuint *pipelines);
using GLGenProgramPipelines = void(*)(GLsizei n, GLuint *pipelines);
using GLGetProgramPipelineiv = void(*)(GLuint pipeline, GLenum pname, GLint *params);
using GLProgramUniform1i = void(*)(GLuint program, GLint location, GLint v0);
using GLProgramUniform1iv = void(*)(GLuint program, GLint location, GLsizei count, const GLint *value);
using GLProgramUniform1f = void(*)(GLuint program, GLint location, GLfloat v0);
using GLProgramUniform1fv = void(*)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
using GLProgramUniform1d = void(*)(GLuint program, GLint location, GLdouble v0);
using GLProgramUniform1dv = void(*)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
using GLProgramUniform1ui = void(*)(GLuint program, GLint location, GLuint v0);
using GLProgramUniform1uiv = void(*)(GLuint program, GLint location, GLsizei count, const GLuint *value);
using GLProgramUniform2i = void(*)(GLuint program, GLint location, GLint v0, GLint v1);
using GLProgramUniform2iv = void(*)(GLuint program, GLint location, GLsizei count, const GLint *value);
using GLProgramUniform2f = void(*)(GLuint program, GLint location, GLfloat v0, GLfloat v1);
using GLProgramUniform2fv = void(*)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
using GLProgramUniform2d = void(*)(GLuint program, GLint location, GLdouble v0, GLdouble v1);
using GLProgramUniform2dv = void(*)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
using GLProgramUniform2ui = void(*)(GLuint program, GLint location, GLuint v0, GLuint v1);
using GLProgramUniform2uiv = void(*)(GLuint program, GLint location, GLsizei count, const GLuint *value);
using GLProgramUniform3i = void(*)(GLuint program, GLint location, GLint v0, GLint v1, GLint v2);
using GLProgramUniform3iv = void(*)(GLuint program, GLint location, GLsizei count, const GLint *value);
using GLProgramUniform3f = void(*)(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
using GLProgramUniform3fv = void(*)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
using GLProgramUniform3d = void(*)(GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2);
using GLProgramUniform3dv = void(*)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
using GLProgramUniform3ui = void(*)(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2);
using GLProgramUniform3uiv = void(*)(GLuint program, GLint location, GLsizei count, const GLuint *value);
using GLProgramUniform4i = void(*)(GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
using GLProgramUniform4iv = void(*)(GLuint program, GLint location, GLsizei count, const GLint *value);
using GLProgramUniform4f = void(*)(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
using GLProgramUniform4fv = void(*)(GLuint program, GLint location, GLsizei count, const GLfloat *value);
using GLProgramUniform4d = void(*)(GLuint program, GLint location, GLdouble v0, GLdouble v1, GLdouble v2, GLdouble v3);
using GLProgramUniform4dv = void(*)(GLuint program, GLint location, GLsizei count, const GLdouble *value);
using GLProgramUniform4ui = void(*)(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
using GLProgramUniform4uiv = void(*)(GLuint program, GLint location, GLsizei count, const GLuint *value);
using GLProgramUniformMatrix2fv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLProgramUniformMatrix3fv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLProgramUniformMatrix4fv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLProgramUniformMatrix2dv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLProgramUniformMatrix3dv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLProgramUniformMatrix4dv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLProgramUniformMatrix2x3fv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLProgramUniformMatrix3x2fv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLProgramUniformMatrix2x4fv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLProgramUniformMatrix4x2fv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLProgramUniformMatrix3x4fv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLProgramUniformMatrix4x3fv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
using GLProgramUniformMatrix2x3dv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLProgramUniformMatrix3x2dv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLProgramUniformMatrix2x4dv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLProgramUniformMatrix4x2dv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLProgramUniformMatrix3x4dv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLProgramUniformMatrix4x3dv = void(*)(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLdouble *value);
using GLValidateProgramPipeline = void(*)(GLuint pipeline);
using GLGetProgramPipelineInfoLog = void(*)(GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
using GLVertexAttribL1d = void(*)(GLuint index, GLdouble x);
using GLVertexAttribL2d = void(*)(GLuint index, GLdouble x, GLdouble y);
using GLVertexAttribL3d = void(*)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
using GLVertexAttribL4d = void(*)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
using GLVertexAttribL1dv = void(*)(GLuint index, const GLdouble *v);
using GLVertexAttribL2dv = void(*)(GLuint index, const GLdouble *v);
using GLVertexAttribL3dv = void(*)(GLuint index, const GLdouble *v);
using GLVertexAttribL4dv = void(*)(GLuint index, const GLdouble *v);
using GLVertexAttribLPointer = void(*)(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
using GLGetVertexAttribLdv = void(*)(GLuint index, GLenum pname, GLdouble *params);
using GLViewportArrayv = void(*)(GLuint first, GLsizei count, const GLfloat *v);
using GLViewportIndexedf = void(*)(GLuint index, GLfloat x, GLfloat y, GLfloat w, GLfloat h);
using GLViewportIndexedfv = void(*)(GLuint index, const GLfloat *v);
using GLScissorArrayv = void(*)(GLuint first, GLsizei count, const GLint *v);
using GLScissorIndexed = void(*)(GLuint index, GLint left, GLint bottom, GLsizei width, GLsizei height);
using GLScissorIndexedv = void(*)(GLuint index, const GLint *v);
using GLDepthRangeArrayv = void(*)(GLuint first, GLsizei count, const GLdouble *v);
using GLDepthRangeIndexed = void(*)(GLuint index, GLdouble n, GLdouble f);
using GLGetFloati_v = void(*)(GLenum target, GLuint index, GLfloat *data);
using GLGetDoublei_v = void(*)(GLenum target, GLuint index, GLdouble *data);
using GLDrawArraysInstancedBaseInstance = void(*)(GLenum mode, GLint first, GLsizei count, GLsizei instancecount, GLuint baseinstance);
using GLDrawElementsInstancedBaseInstance = void(*)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLuint baseinstance);
using GLDrawElementsInstancedBaseVertexBaseInstance = void(*)(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex, GLuint baseinstance);
using GLGetInternalformativ = void(*)(GLenum target, GLenum internalformat, GLenum pname, GLsizei count, GLint *params);
using GLGetActiveAtomicCounterBufferiv = void(*)(GLuint program, GLuint bufferIndex, GLenum pname, GLint *params);
using GLBindImageTexture = void(*)(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
using GLMemoryBarrier = void(*)(GLbitfield barriers);
using GLTexStorage1D = void(*)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width);
using GLTexStorage2D = void(*)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
using GLTexStorage3D = void(*)(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
using GLDrawTransformFeedbackInstanced = void(*)(GLenum mode, GLuint id, GLsizei instancecount);
using GLDrawTransformFeedbackStreamInstanced = void(*)(GLenum mode, GLuint id, GLuint stream, GLsizei instancecount);
using GLClearBufferData = void(*)(GLenum target, GLenum internalformat, GLenum format, GLenum type, const void *data);
using GLClearBufferSubData = void(*)(GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void *data);
using GLDispatchCompute = void(*)(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
using GLDispatchComputeIndirect = void(*)(GLintptr indirect);
using GLCopyImageSubData = void(*)(GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth);
using GLFramebufferParameteri = void(*)(GLenum target, GLenum pname, GLint param);
using GLGetFramebufferParameteriv = void(*)(GLenum target, GLenum pname, GLint *params);
using GLGetInternalformati64v = void(*)(GLenum target, GLenum internalformat, GLenum pname, GLsizei count, GLint64 *params);
using GLInvalidateTexSubImage = void(*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth);
using GLInvalidateTexImage = void(*)(GLuint texture, GLint level);
using GLInvalidateBufferSubData = void(*)(GLuint buffer, GLintptr offset, GLsizeiptr length);
using GLInvalidateBufferData = void(*)(GLuint buffer);
using GLInvalidateFramebuffer = void(*)(GLenum target, GLsizei numAttachments, const GLenum *attachments);
using GLInvalidateSubFramebuffer = void(*)(GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
using GLMultiDrawArraysIndirect = void(*)(GLenum mode, const void *indirect, GLsizei drawcount, GLsizei stride);
using GLMultiDrawElementsIndirect = void(*)(GLenum mode, GLenum type, const void *indirect, GLsizei drawcount, GLsizei stride);
using GLGetProgramInterfaceiv = void(*)(GLuint program, GLenum programInterface, GLenum pname, GLint *params);
using GLGetProgramResourceName = void(*)(GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
using GLGetProgramResourceiv = void(*)(GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei count, GLsizei *length, GLint *params);
using GLShaderStorageBlockBinding = void(*)(GLuint program, GLuint storageBlockIndex, GLuint storageBlockBinding);
using GLTexBufferRange = void(*)(GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
using GLTexStorage2DMultisample = void(*)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
using GLTexStorage3DMultisample = void(*)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
using GLTextureView = void(*)(GLuint texture, GLenum target, GLuint origtexture, GLenum internalformat, GLuint minlevel, GLuint numlevels, GLuint minlayer, GLuint numlayers);
using GLBindVertexBuffer = void(*)(GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
using GLVertexAttribFormat = void(*)(GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
using GLVertexAttribIFormat = void(*)(GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
using GLVertexAttribLFormat = void(*)(GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
using GLVertexAttribBinding = void(*)(GLuint attribindex, GLuint bindingindex);
using GLVertexBindingDivisor = void(*)(GLuint bindingindex, GLuint divisor);
using GLDebugMessageControl = void(*)(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled);
using GLDebugMessageInsert = void(*)(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf);
using GLDebugMessageCallback = void(*)(GLDebugProc callback, const void *userParam);
using GLPushDebugGroup = void(*)(GLenum source, GLuint id, GLsizei length, const GLchar *message);
using GLPopDebugGroup = void(*)(void);
using GLObjectLabel = void(*)(GLenum identifier, GLuint name, GLsizei length, const GLchar *label);
using GLGetObjectLabel = void(*)(GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label);
using GLObjectPtrLabel = void(*)(const void *ptr, GLsizei length, const GLchar *label);
using GLGetObjectPtrLabel = void(*)(const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label);
using GLGetPointerv = void(*)(GLenum pname, void **params);
using GLBufferStorage = void(*)(GLenum target, GLsizeiptr size, const void *data, GLbitfield flags);
using GLClearTexImage = void(*)(GLuint texture, GLint level, GLenum format, GLenum type, const void *data);
using GLClearTexSubImage = void(*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *data);
using GLBindBuffersBase = void(*)(GLenum target, GLuint first, GLsizei count, const GLuint *buffers);
using GLBindBuffersRange = void(*)(GLenum target, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizeiptr *sizes);
using GLBindTextures = void(*)(GLuint first, GLsizei count, const GLuint *textures);
using GLBindSamplers = void(*)(GLuint first, GLsizei count, const GLuint *samplers);
using GLBindImageTextures = void(*)(GLuint first, GLsizei count, const GLuint *textures);
using GLBindVertexBuffers = void(*)(GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides);
using GLClipControl = void(*)(GLenum origin, GLenum depth);
using GLCreateTransformFeedbacks = void(*)(GLsizei n, GLuint *ids);
using GLTransformFeedbackBufferBase = void(*)(GLuint xfb, GLuint index, GLuint buffer);
using GLTransformFeedbackBufferRange = void(*)(GLuint xfb, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
using GLGetTransformFeedbackiv = void(*)(GLuint xfb, GLenum pname, GLint *param);
using GLGetTransformFeedbacki_v = void(*)(GLuint xfb, GLenum pname, GLuint index, GLint *param);
using GLGetTransformFeedbacki64_v = void(*)(GLuint xfb, GLenum pname, GLuint index, GLint64 *param);
using GLCreateBuffers = void(*)(GLsizei n, GLuint *buffers);
using GLNamedBufferStorage = void(*)(GLuint buffer, GLsizeiptr size, const void *data, GLbitfield flags);
using GLNamedBufferData = void(*)(GLuint buffer, GLsizeiptr size, const void *data, GLenum usage);
using GLNamedBufferSubData = void(*)(GLuint buffer, GLintptr offset, GLsizeiptr size, const void *data);
using GLCopyNamedBufferSubData = void(*)(GLuint readBuffer, GLuint writeBuffer, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
using GLClearNamedBufferData = void(*)(GLuint buffer, GLenum internalformat, GLenum format, GLenum type, const void *data);
using GLClearNamedBufferSubData = void(*)(GLuint buffer, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void *data);
using GLFlushMappedNamedBufferRange = void(*)(GLuint buffer, GLintptr offset, GLsizeiptr length);
using GLGetNamedBufferParameteriv = void(*)(GLuint buffer, GLenum pname, GLint *params);
using GLGetNamedBufferParameteri64v = void(*)(GLuint buffer, GLenum pname, GLint64 *params);
using GLGetNamedBufferPointerv = void(*)(GLuint buffer, GLenum pname, void **params);
using GLGetNamedBufferSubData = void(*)(GLuint buffer, GLintptr offset, GLsizeiptr size, void *data);
using GLCreateFramebuffers = void(*)(GLsizei n, GLuint *framebuffers);
using GLNamedFramebufferRenderbuffer = void(*)(GLuint framebuffer, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
using GLNamedFramebufferParameteri = void(*)(GLuint framebuffer, GLenum pname, GLint param);
using GLNamedFramebufferTexture = void(*)(GLuint framebuffer, GLenum attachment, GLuint texture, GLint level);
using GLNamedFramebufferTextureLayer = void(*)(GLuint framebuffer, GLenum attachment, GLuint texture, GLint level, GLint layer);
using GLNamedFramebufferDrawBuffer = void(*)(GLuint framebuffer, GLenum buf);
using GLNamedFramebufferDrawBuffers = void(*)(GLuint framebuffer, GLsizei n, const GLenum *bufs);
using GLNamedFramebufferReadBuffer = void(*)(GLuint framebuffer, GLenum src);
using GLInvalidateNamedFramebufferData = void(*)(GLuint framebuffer, GLsizei numAttachments, const GLenum *attachments);
using GLInvalidateNamedFramebufferSubData = void(*)(GLuint framebuffer, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
using GLClearNamedFramebufferiv = void(*)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLint *value);
using GLClearNamedFramebufferuiv = void(*)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLuint *value);
using GLClearNamedFramebufferfv = void(*)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, const GLfloat *value);
using GLClearNamedFramebufferfi = void(*)(GLuint framebuffer, GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
using GLBlitNamedFramebuffer = void(*)(GLuint readFramebuffer, GLuint drawFramebuffer, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
using GLGetNamedFramebufferParameteriv = void(*)(GLuint framebuffer, GLenum pname, GLint *param);
using GLGetNamedFramebufferAttachmentParameteriv = void(*)(GLuint framebuffer, GLenum attachment, GLenum pname, GLint *params);
using GLCreateRenderbuffers = void(*)(GLsizei n, GLuint *renderbuffers);
using GLNamedRenderbufferStorage = void(*)(GLuint renderbuffer, GLenum internalformat, GLsizei width, GLsizei height);
using GLNamedRenderbufferStorageMultisample = void(*)(GLuint renderbuffer, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
using GLGetNamedRenderbufferParameteriv = void(*)(GLuint renderbuffer, GLenum pname, GLint *params);
using GLCreateTextures = void(*)(GLenum target, GLsizei n, GLuint *textures);
using GLTextureBuffer = void(*)(GLuint texture, GLenum internalformat, GLuint buffer);
using GLTextureBufferRange = void(*)(GLuint texture, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size);
using GLTextureStorage1D = void(*)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width);
using GLTextureStorage2D = void(*)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
using GLTextureStorage3D = void(*)(GLuint texture, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
using GLTextureStorage2DMultisample = void(*)(GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
using GLTextureStorage3DMultisample = void(*)(GLuint texture, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
using GLTextureSubImage1D = void(*)(GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const void *pixels);
using GLTextureSubImage2D = void(*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
using GLTextureSubImage3D = void(*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
using GLCompressedTextureSubImage1D = void(*)(GLuint texture, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const void *data);
using GLCompressedTextureSubImage2D = void(*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
using GLCompressedTextureSubImage3D = void(*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data);
using GLCopyTextureSubImage1D = void(*)(GLuint texture, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
using GLCopyTextureSubImage2D = void(*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
using GLCopyTextureSubImage3D = void(*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
using GLTextureParameterf = void(*)(GLuint texture, GLenum pname, GLfloat param);
using GLTextureParameterfv = void(*)(GLuint texture, GLenum pname, const GLfloat *param);
using GLTextureParameteri = void(*)(GLuint texture, GLenum pname, GLint param);
using GLTextureParameterIiv = void(*)(GLuint texture, GLenum pname, const GLint *params);
using GLTextureParameterIuiv = void(*)(GLuint texture, GLenum pname, const GLuint *params);
using GLTextureParameteriv = void(*)(GLuint texture, GLenum pname, const GLint *param);
using GLGenerateTextureMipmap = void(*)(GLuint texture);
using GLBindTextureUnit = void(*)(GLuint unit, GLuint texture);
using GLGetTextureImage = void(*)(GLuint texture, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
using GLGetCompressedTextureImage = void(*)(GLuint texture, GLint level, GLsizei bufSize, void *pixels);
using GLGetTextureLevelParameterfv = void(*)(GLuint texture, GLint level, GLenum pname, GLfloat *params);
using GLGetTextureLevelParameteriv = void(*)(GLuint texture, GLint level, GLenum pname, GLint *params);
using GLGetTextureParameterfv = void(*)(GLuint texture, GLenum pname, GLfloat *params);
using GLGetTextureParameterIiv = void(*)(GLuint texture, GLenum pname, GLint *params);
using GLGetTextureParameterIuiv = void(*)(GLuint texture, GLenum pname, GLuint *params);
using GLGetTextureParameteriv = void(*)(GLuint texture, GLenum pname, GLint *params);
using GLCreateVertexArrays = void(*)(GLsizei n, GLuint *arrays);
using GLDisableVertexArrayAttrib = void(*)(GLuint vaobj, GLuint index);
using GLEnableVertexArrayAttrib = void(*)(GLuint vaobj, GLuint index);
using GLVertexArrayElementBuffer = void(*)(GLuint vaobj, GLuint buffer);
using GLVertexArrayVertexBuffer = void(*)(GLuint vaobj, GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
using GLVertexArrayVertexBuffers = void(*)(GLuint vaobj, GLuint first, GLsizei count, const GLuint *buffers, const GLintptr *offsets, const GLsizei *strides);
using GLVertexArrayAttribBinding = void(*)(GLuint vaobj, GLuint attribindex, GLuint bindingindex);
using GLVertexArrayAttribFormat = void(*)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
using GLVertexArrayAttribIFormat = void(*)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
using GLVertexArrayAttribLFormat = void(*)(GLuint vaobj, GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
using GLVertexArrayBindingDivisor = void(*)(GLuint vaobj, GLuint bindingindex, GLuint divisor);
using GLGetVertexArrayiv = void(*)(GLuint vaobj, GLenum pname, GLint *param);
using GLGetVertexArrayIndexediv = void(*)(GLuint vaobj, GLuint index, GLenum pname, GLint *param);
using GLGetVertexArrayIndexed64iv = void(*)(GLuint vaobj, GLuint index, GLenum pname, GLint64 *param);
using GLCreateSamplers = void(*)(GLsizei n, GLuint *samplers);
using GLCreateProgramPipelines = void(*)(GLsizei n, GLuint *pipelines);
using GLCreateQueries = void(*)(GLenum target, GLsizei n, GLuint *ids);
using GLGetQueryBufferObjecti64v = void(*)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
using GLGetQueryBufferObjectiv = void(*)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
using GLGetQueryBufferObjectui64v = void(*)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
using GLGetQueryBufferObjectuiv = void(*)(GLuint id, GLuint buffer, GLenum pname, GLintptr offset);
using GLMemoryBarrierByRegion = void(*)(GLbitfield barriers);
using GLGetTextureSubImage = void(*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
using GLGetCompressedTextureSubImage = void(*)(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLsizei bufSize, void *pixels);
using GLGetnCompressedTexImage = void(*)(GLenum target, GLint lod, GLsizei bufSize, void *pixels);
using GLGetnTexImage = void(*)(GLenum target, GLint level, GLenum format, GLenum type, GLsizei bufSize, void *pixels);
using GLGetnUniformdv = void(*)(GLuint program, GLint location, GLsizei bufSize, GLdouble *params);
using GLGetnUniformfv = void(*)(GLuint program, GLint location, GLsizei bufSize, GLfloat *params);
using GLGetnUniformiv = void(*)(GLuint program, GLint location, GLsizei bufSize, GLint *params);
using GLGetnUniformuiv = void(*)(GLuint program, GLint location, GLsizei bufSize, GLuint *params);
using GLReadnPixels = void(*)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data);
using GLGetnMapdv = void(*)(GLenum target, GLenum query, GLsizei bufSize, GLdouble *v);
using GLGetnMapfv = void(*)(GLenum target, GLenum query, GLsizei bufSize, GLfloat *v);
using GLGetnMapiv = void(*)(GLenum target, GLenum query, GLsizei bufSize, GLint *v);
using GLGetnPixelMapfv = void(*)(GLenum map, GLsizei bufSize, GLfloat *values);
using GLGetnPixelMapuiv = void(*)(GLenum map, GLsizei bufSize, GLuint *values);
using GLGetnPixelMapusv = void(*)(GLenum map, GLsizei bufSize, GLushort *values);
using GLGetnPolygonStipple = void(*)(GLsizei bufSize, GLubyte *pattern);
using GLGetnColorTable = void(*)(GLenum target, GLenum format, GLenum type, GLsizei bufSize, void *table);
using GLGetnConvolutionFilter = void(*)(GLenum target, GLenum format, GLenum type, GLsizei bufSize, void *image);
using GLGetnSeparableFilter = void(*)(GLenum target, GLenum format, GLenum type, GLsizei rowBufSize, void *row, GLsizei columnBufSize, void *column, void *span);
using GLGetnHistogram = void(*)(GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, void *values);
using GLGetnMinmax = void(*)(GLenum target, GLboolean reset, GLenum format, GLenum type, GLsizei bufSize, void *values);
using GLTextureBarrier = void(*)(void);
using GLSpecializeShader = void(*)(GLuint shader, const GLchar *pEntryPoint, GLuint numSpecializationConstants, const GLuint *pConstantIndex, const GLuint *pConstantValue);
using GLMultiDrawArraysIndirectCount = void(*)(GLenum mode, const void *indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride);
using GLMultiDrawElementsIndirectCount = void(*)(GLenum mode, GLenum type, const void *indirect, GLintptr drawcount, GLsizei maxdrawcount, GLsizei stride);
using GLPolygonOffsetClamp = void(*)(GLfloat factor, GLfloat units, GLfloat clamp);
using GLBlendBarrier = void(*)(void);
using GLPrimitiveBoundingBox = void(*)(GLfloat minX, GLfloat minY, GLfloat minZ, GLfloat minW, GLfloat maxX, GLfloat maxY, GLfloat maxZ, GLfloat maxW);

extern GLCullFace glCullFace;
extern GLFrontFace glFrontFace;
extern GLHint glHint;
extern GLLineWidth glLineWidth;
extern GLPointSize glPointSize;
extern GLPolygonMode glPolygonMode;
extern GLScissor glScissor;
extern GLTexParameterf glTexParameterf;
extern GLTexParameterfv glTexParameterfv;
extern GLTexParameteri glTexParameteri;
extern GLTexParameteriv glTexParameteriv;
extern GLTexImage1D glTexImage1D;
extern GLTexImage2D glTexImage2D;
extern GLDrawBuffer glDrawBuffer;
extern GLClear glClear;
extern GLClearColor glClearColor;
extern GLClearStencil glClearStencil;
extern GLClearDepth glClearDepth;
extern GLStencilMask glStencilMask;
extern GLColorMask glColorMask;
extern GLDepthMask glDepthMask;
extern GLDisable glDisable;
extern GLEnable glEnable;
extern GLFinish glFinish;
extern GLFlush glFlush;
extern GLBlendFunc glBlendFunc;
extern GLLogicOp glLogicOp;
extern GLStencilFunc glStencilFunc;
extern GLStencilOp glStencilOp;
extern GLDepthFunc glDepthFunc;
extern GLPixelStoref glPixelStoref;
extern GLPixelStorei glPixelStorei;
extern GLReadBuffer glReadBuffer;
extern GLReadPixels glReadPixels;
extern GLGetBooleanv glGetBooleanv;
extern GLGetDoublev glGetDoublev;
extern GLGetFloatv glGetFloatv;
extern GLGetIntegerv glGetIntegerv;
extern GLGetTexImage glGetTexImage;
extern GLGetTexParameterfv glGetTexParameterfv;
extern GLGetTexParameteriv glGetTexParameteriv;
extern GLGetTexLevelParameterfv glGetTexLevelParameterfv;
extern GLGetTexLevelParameteriv glGetTexLevelParameteriv;
extern GLDepthRange glDepthRange;
extern GLViewport glViewport;
extern GLDrawArrays glDrawArrays;
extern GLDrawElements glDrawElements;
extern GLPolygonOffset glPolygonOffset;
extern GLCopyTexImage1D glCopyTexImage1D;
extern GLCopyTexImage2D glCopyTexImage2D;
extern GLCopyTexSubImage1D glCopyTexSubImage1D;
extern GLCopyTexSubImage2D glCopyTexSubImage2D;
extern GLTexSubImage1D glTexSubImage1D;
extern GLTexSubImage2D glTexSubImage2D;
extern GLBindTexture glBindTexture;
extern GLDeleteTextures glDeleteTextures;
extern GLGenTextures glGenTextures;
extern GLDrawRangeElements glDrawRangeElements;
extern GLTexImage3D glTexImage3D;
extern GLTexSubImage3D glTexSubImage3D;
extern GLCopyTexSubImage3D glCopyTexSubImage3D;
extern GLActiveTexture glActiveTexture;
extern GLSampleCoverage glSampleCoverage;
extern GLCompressedTexImage3D glCompressedTexImage3D;
extern GLCompressedTexImage2D glCompressedTexImage2D;
extern GLCompressedTexImage1D glCompressedTexImage1D;
extern GLCompressedTexSubImage3D glCompressedTexSubImage3D;
extern GLCompressedTexSubImage2D glCompressedTexSubImage2D;
extern GLCompressedTexSubImage1D glCompressedTexSubImage1D;
extern GLGetCompressedTexImage glGetCompressedTexImage;
extern GLBlendFuncSeparate glBlendFuncSeparate;
extern GLMultiDrawArrays glMultiDrawArrays;
extern GLMultiDrawElements glMultiDrawElements;
extern GLPointParameterf glPointParameterf;
extern GLPointParameterfv glPointParameterfv;
extern GLPointParameteri glPointParameteri;
extern GLPointParameteriv glPointParameteriv;
extern GLBlendColor glBlendColor;
extern GLBlendEquation glBlendEquation;
extern GLGenQueries glGenQueries;
extern GLDeleteQueries glDeleteQueries;
extern GLBeginQuery glBeginQuery;
extern GLEndQuery glEndQuery;
extern GLGetQueryiv glGetQueryiv;
extern GLGetQueryObjectiv glGetQueryObjectiv;
extern GLGetQueryObjectuiv glGetQueryObjectuiv;
extern GLBindBuffer glBindBuffer;
extern GLDeleteBuffers glDeleteBuffers;
extern GLGenBuffers glGenBuffers;
extern GLBufferData glBufferData;
extern GLBufferSubData glBufferSubData;
extern GLGetBufferSubData glGetBufferSubData;
extern GLGetBufferParameteriv glGetBufferParameteriv;
extern GLGetBufferPointerv glGetBufferPointerv;
extern GLBlendEquationSeparate glBlendEquationSeparate;
extern GLDrawBuffers glDrawBuffers;
extern GLStencilOpSeparate glStencilOpSeparate;
extern GLStencilFuncSeparate glStencilFuncSeparate;
extern GLStencilMaskSeparate glStencilMaskSeparate;
extern GLAttachShader glAttachShader;
extern GLBindAttribLocation glBindAttribLocation;
extern GLCompileShader glCompileShader;
extern GLDeleteProgram glDeleteProgram;
extern GLDeleteShader glDeleteShader;
extern GLDetachShader glDetachShader;
extern GLDisableVertexAttribArray glDisableVertexAttribArray;
extern GLEnableVertexAttribArray glEnableVertexAttribArray;
extern GLGetActiveAttrib glGetActiveAttrib;
extern GLGetActiveUniform glGetActiveUniform;
extern GLGetAttachedShaders glGetAttachedShaders;
extern GLGetProgramiv glGetProgramiv;
extern GLGetProgramInfoLog glGetProgramInfoLog;
extern GLGetShaderiv glGetShaderiv;
extern GLGetShaderInfoLog glGetShaderInfoLog;
extern GLGetShaderSource glGetShaderSource;
extern GLGetUniformfv glGetUniformfv;
extern GLGetUniformiv glGetUniformiv;
extern GLGetVertexAttribdv glGetVertexAttribdv;
extern GLGetVertexAttribfv glGetVertexAttribfv;
extern GLGetVertexAttribiv glGetVertexAttribiv;
extern GLGetVertexAttribPointerv glGetVertexAttribPointerv;
extern GLLinkProgram glLinkProgram;
extern GLShaderSource glShaderSource;
extern GLUseProgram glUseProgram;
extern GLUniform1f glUniform1f;
extern GLUniform2f glUniform2f;
extern GLUniform3f glUniform3f;
extern GLUniform4f glUniform4f;
extern GLUniform1i glUniform1i;
extern GLUniform2i glUniform2i;
extern GLUniform3i glUniform3i;
extern GLUniform4i glUniform4i;
extern GLUniform1fv glUniform1fv;
extern GLUniform2fv glUniform2fv;
extern GLUniform3fv glUniform3fv;
extern GLUniform4fv glUniform4fv;
extern GLUniform1iv glUniform1iv;
extern GLUniform2iv glUniform2iv;
extern GLUniform3iv glUniform3iv;
extern GLUniform4iv glUniform4iv;
extern GLUniformMatrix2fv glUniformMatrix2fv;
extern GLUniformMatrix3fv glUniformMatrix3fv;
extern GLUniformMatrix4fv glUniformMatrix4fv;
extern GLValidateProgram glValidateProgram;
extern GLVertexAttrib1d glVertexAttrib1d;
extern GLVertexAttrib1dv glVertexAttrib1dv;
extern GLVertexAttrib1f glVertexAttrib1f;
extern GLVertexAttrib1fv glVertexAttrib1fv;
extern GLVertexAttrib1s glVertexAttrib1s;
extern GLVertexAttrib1sv glVertexAttrib1sv;
extern GLVertexAttrib2d glVertexAttrib2d;
extern GLVertexAttrib2dv glVertexAttrib2dv;
extern GLVertexAttrib2f glVertexAttrib2f;
extern GLVertexAttrib2fv glVertexAttrib2fv;
extern GLVertexAttrib2s glVertexAttrib2s;
extern GLVertexAttrib2sv glVertexAttrib2sv;
extern GLVertexAttrib3d glVertexAttrib3d;
extern GLVertexAttrib3dv glVertexAttrib3dv;
extern GLVertexAttrib3f glVertexAttrib3f;
extern GLVertexAttrib3fv glVertexAttrib3fv;
extern GLVertexAttrib3s glVertexAttrib3s;
extern GLVertexAttrib3sv glVertexAttrib3sv;
extern GLVertexAttrib4Nbv glVertexAttrib4Nbv;
extern GLVertexAttrib4Niv glVertexAttrib4Niv;
extern GLVertexAttrib4Nsv glVertexAttrib4Nsv;
extern GLVertexAttrib4Nub glVertexAttrib4Nub;
extern GLVertexAttrib4Nubv glVertexAttrib4Nubv;
extern GLVertexAttrib4Nuiv glVertexAttrib4Nuiv;
extern GLVertexAttrib4Nusv glVertexAttrib4Nusv;
extern GLVertexAttrib4bv glVertexAttrib4bv;
extern GLVertexAttrib4d glVertexAttrib4d;
extern GLVertexAttrib4dv glVertexAttrib4dv;
extern GLVertexAttrib4f glVertexAttrib4f;
extern GLVertexAttrib4fv glVertexAttrib4fv;
extern GLVertexAttrib4iv glVertexAttrib4iv;
extern GLVertexAttrib4s glVertexAttrib4s;
extern GLVertexAttrib4sv glVertexAttrib4sv;
extern GLVertexAttrib4ubv glVertexAttrib4ubv;
extern GLVertexAttrib4uiv glVertexAttrib4uiv;
extern GLVertexAttrib4usv glVertexAttrib4usv;
extern GLVertexAttribPointer glVertexAttribPointer;
extern GLUniformMatrix2x3fv glUniformMatrix2x3fv;
extern GLUniformMatrix3x2fv glUniformMatrix3x2fv;
extern GLUniformMatrix2x4fv glUniformMatrix2x4fv;
extern GLUniformMatrix4x2fv glUniformMatrix4x2fv;
extern GLUniformMatrix3x4fv glUniformMatrix3x4fv;
extern GLUniformMatrix4x3fv glUniformMatrix4x3fv;
extern GLColorMaski glColorMaski;
extern GLGetBooleani_v glGetBooleani_v;
extern GLGetIntegeri_v glGetIntegeri_v;
extern GLEnablei glEnablei;
extern GLDisablei glDisablei;
extern GLBeginTransformFeedback glBeginTransformFeedback;
extern GLEndTransformFeedback glEndTransformFeedback;
extern GLBindBufferRange glBindBufferRange;
extern GLBindBufferBase glBindBufferBase;
extern GLTransformFeedbackVaryings glTransformFeedbackVaryings;
extern GLGetTransformFeedbackVarying glGetTransformFeedbackVarying;
extern GLClampColor glClampColor;
extern GLBeginConditionalRender glBeginConditionalRender;
extern GLEndConditionalRender glEndConditionalRender;
extern GLVertexAttribIPointer glVertexAttribIPointer;
extern GLGetVertexAttribIiv glGetVertexAttribIiv;
extern GLGetVertexAttribIuiv glGetVertexAttribIuiv;
extern GLVertexAttribI1i glVertexAttribI1i;
extern GLVertexAttribI2i glVertexAttribI2i;
extern GLVertexAttribI3i glVertexAttribI3i;
extern GLVertexAttribI4i glVertexAttribI4i;
extern GLVertexAttribI1ui glVertexAttribI1ui;
extern GLVertexAttribI2ui glVertexAttribI2ui;
extern GLVertexAttribI3ui glVertexAttribI3ui;
extern GLVertexAttribI4ui glVertexAttribI4ui;
extern GLVertexAttribI1iv glVertexAttribI1iv;
extern GLVertexAttribI2iv glVertexAttribI2iv;
extern GLVertexAttribI3iv glVertexAttribI3iv;
extern GLVertexAttribI4iv glVertexAttribI4iv;
extern GLVertexAttribI1uiv glVertexAttribI1uiv;
extern GLVertexAttribI2uiv glVertexAttribI2uiv;
extern GLVertexAttribI3uiv glVertexAttribI3uiv;
extern GLVertexAttribI4uiv glVertexAttribI4uiv;
extern GLVertexAttribI4bv glVertexAttribI4bv;
extern GLVertexAttribI4sv glVertexAttribI4sv;
extern GLVertexAttribI4ubv glVertexAttribI4ubv;
extern GLVertexAttribI4usv glVertexAttribI4usv;
extern GLGetUniformuiv glGetUniformuiv;
extern GLBindFragDataLocation glBindFragDataLocation;
extern GLUniform1ui glUniform1ui;
extern GLUniform2ui glUniform2ui;
extern GLUniform3ui glUniform3ui;
extern GLUniform4ui glUniform4ui;
extern GLUniform1uiv glUniform1uiv;
extern GLUniform2uiv glUniform2uiv;
extern GLUniform3uiv glUniform3uiv;
extern GLUniform4uiv glUniform4uiv;
extern GLTexParameterIiv glTexParameterIiv;
extern GLTexParameterIuiv glTexParameterIuiv;
extern GLGetTexParameterIiv glGetTexParameterIiv;
extern GLGetTexParameterIuiv glGetTexParameterIuiv;
extern GLClearBufferiv glClearBufferiv;
extern GLClearBufferuiv glClearBufferuiv;
extern GLClearBufferfv glClearBufferfv;
extern GLClearBufferfi glClearBufferfi;
extern GLBindRenderbuffer glBindRenderbuffer;
extern GLDeleteRenderbuffers glDeleteRenderbuffers;
extern GLGenRenderbuffers glGenRenderbuffers;
extern GLRenderbufferStorage glRenderbufferStorage;
extern GLGetRenderbufferParameteriv glGetRenderbufferParameteriv;
extern GLBindFramebuffer glBindFramebuffer;
extern GLDeleteFramebuffers glDeleteFramebuffers;
extern GLGenFramebuffers glGenFramebuffers;
extern GLFramebufferTexture1D glFramebufferTexture1D;
extern GLFramebufferTexture2D glFramebufferTexture2D;
extern GLFramebufferTexture3D glFramebufferTexture3D;
extern GLFramebufferRenderbuffer glFramebufferRenderbuffer;
extern GLGetFramebufferAttachmentParameteriv glGetFramebufferAttachmentParameteriv;
extern GLGenerateMipmap glGenerateMipmap;
extern GLBlitFramebuffer glBlitFramebuffer;
extern GLRenderbufferStorageMultisample glRenderbufferStorageMultisample;
extern GLFramebufferTextureLayer glFramebufferTextureLayer;
extern GLFlushMappedBufferRange glFlushMappedBufferRange;
extern GLBindVertexArray glBindVertexArray;
extern GLDeleteVertexArrays glDeleteVertexArrays;
extern GLGenVertexArrays glGenVertexArrays;
extern GLDrawArraysInstanced glDrawArraysInstanced;
extern GLDrawElementsInstanced glDrawElementsInstanced;
extern GLTexBuffer glTexBuffer;
extern GLPrimitiveRestartIndex glPrimitiveRestartIndex;
extern GLCopyBufferSubData glCopyBufferSubData;
extern GLGetUniformIndices glGetUniformIndices;
extern GLGetActiveUniformsiv glGetActiveUniformsiv;
extern GLGetActiveUniformName glGetActiveUniformName;
extern GLGetActiveUniformBlockiv glGetActiveUniformBlockiv;
extern GLGetActiveUniformBlockName glGetActiveUniformBlockName;
extern GLUniformBlockBinding glUniformBlockBinding;
extern GLDrawElementsBaseVertex glDrawElementsBaseVertex;
extern GLDrawRangeElementsBaseVertex glDrawRangeElementsBaseVertex;
extern GLDrawElementsInstancedBaseVertex glDrawElementsInstancedBaseVertex;
extern GLMultiDrawElementsBaseVertex glMultiDrawElementsBaseVertex;
extern GLProvokingVertex glProvokingVertex;
extern GLDeleteSync glDeleteSync;
extern GLWaitSync glWaitSync;
extern GLGetInteger64v glGetInteger64v;
extern GLGetSynciv glGetSynciv;
extern GLGetInteger64i_v glGetInteger64i_v;
extern GLGetBufferParameteri64v glGetBufferParameteri64v;
extern GLFramebufferTexture glFramebufferTexture;
extern GLTexImage2DMultisample glTexImage2DMultisample;
extern GLTexImage3DMultisample glTexImage3DMultisample;
extern GLGetMultisamplefv glGetMultisamplefv;
extern GLSampleMaski glSampleMaski;
extern GLBindFragDataLocationIndexed glBindFragDataLocationIndexed;
extern GLGenSamplers glGenSamplers;
extern GLDeleteSamplers glDeleteSamplers;
extern GLBindSampler glBindSampler;
extern GLSamplerParameteri glSamplerParameteri;
extern GLSamplerParameteriv glSamplerParameteriv;
extern GLSamplerParameterf glSamplerParameterf;
extern GLSamplerParameterfv glSamplerParameterfv;
extern GLSamplerParameterIiv glSamplerParameterIiv;
extern GLSamplerParameterIuiv glSamplerParameterIuiv;
extern GLGetSamplerParameteriv glGetSamplerParameteriv;
extern GLGetSamplerParameterIiv glGetSamplerParameterIiv;
extern GLGetSamplerParameterfv glGetSamplerParameterfv;
extern GLGetSamplerParameterIuiv glGetSamplerParameterIuiv;
extern GLQueryCounter glQueryCounter;
extern GLGetQueryObjecti64v glGetQueryObjecti64v;
extern GLGetQueryObjectui64v glGetQueryObjectui64v;
extern GLVertexAttribDivisor glVertexAttribDivisor;
extern GLVertexAttribP1ui glVertexAttribP1ui;
extern GLVertexAttribP1uiv glVertexAttribP1uiv;
extern GLVertexAttribP2ui glVertexAttribP2ui;
extern GLVertexAttribP2uiv glVertexAttribP2uiv;
extern GLVertexAttribP3ui glVertexAttribP3ui;
extern GLVertexAttribP3uiv glVertexAttribP3uiv;
extern GLVertexAttribP4ui glVertexAttribP4ui;
extern GLVertexAttribP4uiv glVertexAttribP4uiv;
extern GLVertexP2ui glVertexP2ui;
extern GLVertexP2uiv glVertexP2uiv;
extern GLVertexP3ui glVertexP3ui;
extern GLVertexP3uiv glVertexP3uiv;
extern GLVertexP4ui glVertexP4ui;
extern GLVertexP4uiv glVertexP4uiv;
extern GLTexCoordP1ui glTexCoordP1ui;
extern GLTexCoordP1uiv glTexCoordP1uiv;
extern GLTexCoordP2ui glTexCoordP2ui;
extern GLTexCoordP2uiv glTexCoordP2uiv;
extern GLTexCoordP3ui glTexCoordP3ui;
extern GLTexCoordP3uiv glTexCoordP3uiv;
extern GLTexCoordP4ui glTexCoordP4ui;
extern GLTexCoordP4uiv glTexCoordP4uiv;
extern GLMultiTexCoordP1ui glMultiTexCoordP1ui;
extern GLMultiTexCoordP1uiv glMultiTexCoordP1uiv;
extern GLMultiTexCoordP2ui glMultiTexCoordP2ui;
extern GLMultiTexCoordP2uiv glMultiTexCoordP2uiv;
extern GLMultiTexCoordP3ui glMultiTexCoordP3ui;
extern GLMultiTexCoordP3uiv glMultiTexCoordP3uiv;
extern GLMultiTexCoordP4ui glMultiTexCoordP4ui;
extern GLMultiTexCoordP4uiv glMultiTexCoordP4uiv;
extern GLNormalP3ui glNormalP3ui;
extern GLNormalP3uiv glNormalP3uiv;
extern GLColorP3ui glColorP3ui;
extern GLColorP3uiv glColorP3uiv;
extern GLColorP4ui glColorP4ui;
extern GLColorP4uiv glColorP4uiv;
extern GLSecondaryColorP3ui glSecondaryColorP3ui;
extern GLSecondaryColorP3uiv glSecondaryColorP3uiv;
extern GLMinSampleShading glMinSampleShading;
extern GLBlendEquationi glBlendEquationi;
extern GLBlendEquationSeparatei glBlendEquationSeparatei;
extern GLBlendFunci glBlendFunci;
extern GLBlendFuncSeparatei glBlendFuncSeparatei;
extern GLDrawArraysIndirect glDrawArraysIndirect;
extern GLDrawElementsIndirect glDrawElementsIndirect;
extern GLUniform1d glUniform1d;
extern GLUniform2d glUniform2d;
extern GLUniform3d glUniform3d;
extern GLUniform4d glUniform4d;
extern GLUniform1dv glUniform1dv;
extern GLUniform2dv glUniform2dv;
extern GLUniform3dv glUniform3dv;
extern GLUniform4dv glUniform4dv;
extern GLUniformMatrix2dv glUniformMatrix2dv;
extern GLUniformMatrix3dv glUniformMatrix3dv;
extern GLUniformMatrix4dv glUniformMatrix4dv;
extern GLUniformMatrix2x3dv glUniformMatrix2x3dv;
extern GLUniformMatrix2x4dv glUniformMatrix2x4dv;
extern GLUniformMatrix3x2dv glUniformMatrix3x2dv;
extern GLUniformMatrix3x4dv glUniformMatrix3x4dv;
extern GLUniformMatrix4x2dv glUniformMatrix4x2dv;
extern GLUniformMatrix4x3dv glUniformMatrix4x3dv;
extern GLGetUniformdv glGetUniformdv;
extern GLGetActiveSubroutineUniformiv glGetActiveSubroutineUniformiv;
extern GLGetActiveSubroutineUniformName glGetActiveSubroutineUniformName;
extern GLGetActiveSubroutineName glGetActiveSubroutineName;
extern GLUniformSubroutinesuiv glUniformSubroutinesuiv;
extern GLGetUniformSubroutineuiv glGetUniformSubroutineuiv;
extern GLGetProgramStageiv glGetProgramStageiv;
extern GLPatchParameteri glPatchParameteri;
extern GLPatchParameterfv glPatchParameterfv;
extern GLBindTransformFeedback glBindTransformFeedback;
extern GLDeleteTransformFeedbacks glDeleteTransformFeedbacks;
extern GLGenTransformFeedbacks glGenTransformFeedbacks;
extern GLPauseTransformFeedback glPauseTransformFeedback;
extern GLResumeTransformFeedback glResumeTransformFeedback;
extern GLDrawTransformFeedback glDrawTransformFeedback;
extern GLDrawTransformFeedbackStream glDrawTransformFeedbackStream;
extern GLBeginQueryIndexed glBeginQueryIndexed;
extern GLEndQueryIndexed glEndQueryIndexed;
extern GLGetQueryIndexediv glGetQueryIndexediv;
extern GLReleaseShaderCompiler glReleaseShaderCompiler;
extern GLShaderBinary glShaderBinary;
extern GLGetShaderPrecisionFormat glGetShaderPrecisionFormat;
extern GLDepthRangef glDepthRangef;
extern GLClearDepthf glClearDepthf;
extern GLGetProgramBinary glGetProgramBinary;
extern GLProgramBinary glProgramBinary;
extern GLProgramParameteri glProgramParameteri;
extern GLUseProgramStages glUseProgramStages;
extern GLActiveShaderProgram glActiveShaderProgram;
extern GLBindProgramPipeline glBindProgramPipeline;
extern GLDeleteProgramPipelines glDeleteProgramPipelines;
extern GLGenProgramPipelines glGenProgramPipelines;
extern GLGetProgramPipelineiv glGetProgramPipelineiv;
extern GLProgramUniform1i glProgramUniform1i;
extern GLProgramUniform1iv glProgramUniform1iv;
extern GLProgramUniform1f glProgramUniform1f;
extern GLProgramUniform1fv glProgramUniform1fv;
extern GLProgramUniform1d glProgramUniform1d;
extern GLProgramUniform1dv glProgramUniform1dv;
extern GLProgramUniform1ui glProgramUniform1ui;
extern GLProgramUniform1uiv glProgramUniform1uiv;
extern GLProgramUniform2i glProgramUniform2i;
extern GLProgramUniform2iv glProgramUniform2iv;
extern GLProgramUniform2f glProgramUniform2f;
extern GLProgramUniform2fv glProgramUniform2fv;
extern GLProgramUniform2d glProgramUniform2d;
extern GLProgramUniform2dv glProgramUniform2dv;
extern GLProgramUniform2ui glProgramUniform2ui;
extern GLProgramUniform2uiv glProgramUniform2uiv;
extern GLProgramUniform3i glProgramUniform3i;
extern GLProgramUniform3iv glProgramUniform3iv;
extern GLProgramUniform3f glProgramUniform3f;
extern GLProgramUniform3fv glProgramUniform3fv;
extern GLProgramUniform3d glProgramUniform3d;
extern GLProgramUniform3dv glProgramUniform3dv;
extern GLProgramUniform3ui glProgramUniform3ui;
extern GLProgramUniform3uiv glProgramUniform3uiv;
extern GLProgramUniform4i glProgramUniform4i;
extern GLProgramUniform4iv glProgramUniform4iv;
extern GLProgramUniform4f glProgramUniform4f;
extern GLProgramUniform4fv glProgramUniform4fv;
extern GLProgramUniform4d glProgramUniform4d;
extern GLProgramUniform4dv glProgramUniform4dv;
extern GLProgramUniform4ui glProgramUniform4ui;
extern GLProgramUniform4uiv glProgramUniform4uiv;
extern GLProgramUniformMatrix2fv glProgramUniformMatrix2fv;
extern GLProgramUniformMatrix3fv glProgramUniformMatrix3fv;
extern GLProgramUniformMatrix4fv glProgramUniformMatrix4fv;
extern GLProgramUniformMatrix2dv glProgramUniformMatrix2dv;
extern GLProgramUniformMatrix3dv glProgramUniformMatrix3dv;
extern GLProgramUniformMatrix4dv glProgramUniformMatrix4dv;
extern GLProgramUniformMatrix2x3fv glProgramUniformMatrix2x3fv;
extern GLProgramUniformMatrix3x2fv glProgramUniformMatrix3x2fv;
extern GLProgramUniformMatrix2x4fv glProgramUniformMatrix2x4fv;
extern GLProgramUniformMatrix4x2fv glProgramUniformMatrix4x2fv;
extern GLProgramUniformMatrix3x4fv glProgramUniformMatrix3x4fv;
extern GLProgramUniformMatrix4x3fv glProgramUniformMatrix4x3fv;
extern GLProgramUniformMatrix2x3dv glProgramUniformMatrix2x3dv;
extern GLProgramUniformMatrix3x2dv glProgramUniformMatrix3x2dv;
extern GLProgramUniformMatrix2x4dv glProgramUniformMatrix2x4dv;
extern GLProgramUniformMatrix4x2dv glProgramUniformMatrix4x2dv;
extern GLProgramUniformMatrix3x4dv glProgramUniformMatrix3x4dv;
extern GLProgramUniformMatrix4x3dv glProgramUniformMatrix4x3dv;
extern GLValidateProgramPipeline glValidateProgramPipeline;
extern GLGetProgramPipelineInfoLog glGetProgramPipelineInfoLog;
extern GLVertexAttribL1d glVertexAttribL1d;
extern GLVertexAttribL2d glVertexAttribL2d;
extern GLVertexAttribL3d glVertexAttribL3d;
extern GLVertexAttribL4d glVertexAttribL4d;
extern GLVertexAttribL1dv glVertexAttribL1dv;
extern GLVertexAttribL2dv glVertexAttribL2dv;
extern GLVertexAttribL3dv glVertexAttribL3dv;
extern GLVertexAttribL4dv glVertexAttribL4dv;
extern GLVertexAttribLPointer glVertexAttribLPointer;
extern GLGetVertexAttribLdv glGetVertexAttribLdv;
extern GLViewportArrayv glViewportArrayv;
extern GLViewportIndexedf glViewportIndexedf;
extern GLViewportIndexedfv glViewportIndexedfv;
extern GLScissorArrayv glScissorArrayv;
extern GLScissorIndexed glScissorIndexed;
extern GLScissorIndexedv glScissorIndexedv;
extern GLDepthRangeArrayv glDepthRangeArrayv;
extern GLDepthRangeIndexed glDepthRangeIndexed;
extern GLGetFloati_v glGetFloati_v;
extern GLGetDoublei_v glGetDoublei_v;
extern GLDrawArraysInstancedBaseInstance glDrawArraysInstancedBaseInstance;
extern GLDrawElementsInstancedBaseInstance glDrawElementsInstancedBaseInstance;
extern GLDrawElementsInstancedBaseVertexBaseInstance glDrawElementsInstancedBaseVertexBaseInstance;
extern GLGetInternalformativ glGetInternalformativ;
extern GLGetActiveAtomicCounterBufferiv glGetActiveAtomicCounterBufferiv;
extern GLBindImageTexture glBindImageTexture;
extern GLMemoryBarrier glMemoryBarrier;
extern GLTexStorage1D glTexStorage1D;
extern GLTexStorage2D glTexStorage2D;
extern GLTexStorage3D glTexStorage3D;
extern GLDrawTransformFeedbackInstanced glDrawTransformFeedbackInstanced;
extern GLDrawTransformFeedbackStreamInstanced glDrawTransformFeedbackStreamInstanced;
extern GLClearBufferData glClearBufferData;
extern GLClearBufferSubData glClearBufferSubData;
extern GLDispatchCompute glDispatchCompute;
extern GLDispatchComputeIndirect glDispatchComputeIndirect;
extern GLCopyImageSubData glCopyImageSubData;
extern GLFramebufferParameteri glFramebufferParameteri;
extern GLGetFramebufferParameteriv glGetFramebufferParameteriv;
extern GLGetInternalformati64v glGetInternalformati64v;
extern GLInvalidateTexSubImage glInvalidateTexSubImage;
extern GLInvalidateTexImage glInvalidateTexImage;
extern GLInvalidateBufferSubData glInvalidateBufferSubData;
extern GLInvalidateBufferData glInvalidateBufferData;
extern GLInvalidateFramebuffer glInvalidateFramebuffer;
extern GLInvalidateSubFramebuffer glInvalidateSubFramebuffer;
extern GLMultiDrawArraysIndirect glMultiDrawArraysIndirect;
extern GLMultiDrawElementsIndirect glMultiDrawElementsIndirect;
extern GLGetProgramInterfaceiv glGetProgramInterfaceiv;
extern GLGetProgramResourceName glGetProgramResourceName;
extern GLGetProgramResourceiv glGetProgramResourceiv;
extern GLShaderStorageBlockBinding glShaderStorageBlockBinding;
extern GLTexBufferRange glTexBufferRange;
extern GLTexStorage2DMultisample glTexStorage2DMultisample;
extern GLTexStorage3DMultisample glTexStorage3DMultisample;
extern GLTextureView glTextureView;
extern GLBindVertexBuffer glBindVertexBuffer;
extern GLVertexAttribFormat glVertexAttribFormat;
extern GLVertexAttribIFormat glVertexAttribIFormat;
extern GLVertexAttribLFormat glVertexAttribLFormat;
extern GLVertexAttribBinding glVertexAttribBinding;
extern GLVertexBindingDivisor glVertexBindingDivisor;
extern GLDebugMessageControl glDebugMessageControl;
extern GLDebugMessageInsert glDebugMessageInsert;
extern GLDebugMessageCallback glDebugMessageCallback;
extern GLPushDebugGroup glPushDebugGroup;
extern GLPopDebugGroup glPopDebugGroup;
extern GLObjectLabel glObjectLabel;
extern GLGetObjectLabel glGetObjectLabel;
extern GLObjectPtrLabel glObjectPtrLabel;
extern GLGetObjectPtrLabel glGetObjectPtrLabel;
extern GLGetPointerv glGetPointerv;
extern GLBufferStorage glBufferStorage;
extern GLClearTexImage glClearTexImage;
extern GLClearTexSubImage glClearTexSubImage;
extern GLBindBuffersBase glBindBuffersBase;
extern GLBindBuffersRange glBindBuffersRange;
extern GLBindTextures glBindTextures;
extern GLBindSamplers glBindSamplers;
extern GLBindImageTextures glBindImageTextures;
extern GLBindVertexBuffers glBindVertexBuffers;
extern GLClipControl glClipControl;
extern GLCreateTransformFeedbacks glCreateTransformFeedbacks;
extern GLTransformFeedbackBufferBase glTransformFeedbackBufferBase;
extern GLTransformFeedbackBufferRange glTransformFeedbackBufferRange;
extern GLGetTransformFeedbackiv glGetTransformFeedbackiv;
extern GLGetTransformFeedbacki_v glGetTransformFeedbacki_v;
extern GLGetTransformFeedbacki64_v glGetTransformFeedbacki64_v;
extern GLCreateBuffers glCreateBuffers;
extern GLNamedBufferStorage glNamedBufferStorage;
extern GLNamedBufferData glNamedBufferData;
extern GLNamedBufferSubData glNamedBufferSubData;
extern GLCopyNamedBufferSubData glCopyNamedBufferSubData;
extern GLClearNamedBufferData glClearNamedBufferData;
extern GLClearNamedBufferSubData glClearNamedBufferSubData;
extern GLFlushMappedNamedBufferRange glFlushMappedNamedBufferRange;
extern GLGetNamedBufferParameteriv glGetNamedBufferParameteriv;
extern GLGetNamedBufferParameteri64v glGetNamedBufferParameteri64v;
extern GLGetNamedBufferPointerv glGetNamedBufferPointerv;
extern GLGetNamedBufferSubData glGetNamedBufferSubData;
extern GLCreateFramebuffers glCreateFramebuffers;
extern GLNamedFramebufferRenderbuffer glNamedFramebufferRenderbuffer;
extern GLNamedFramebufferParameteri glNamedFramebufferParameteri;
extern GLNamedFramebufferTexture glNamedFramebufferTexture;
extern GLNamedFramebufferTextureLayer glNamedFramebufferTextureLayer;
extern GLNamedFramebufferDrawBuffer glNamedFramebufferDrawBuffer;
extern GLNamedFramebufferDrawBuffers glNamedFramebufferDrawBuffers;
extern GLNamedFramebufferReadBuffer glNamedFramebufferReadBuffer;
extern GLInvalidateNamedFramebufferData glInvalidateNamedFramebufferData;
extern GLInvalidateNamedFramebufferSubData glInvalidateNamedFramebufferSubData;
extern GLClearNamedFramebufferiv glClearNamedFramebufferiv;
extern GLClearNamedFramebufferuiv glClearNamedFramebufferuiv;
extern GLClearNamedFramebufferfv glClearNamedFramebufferfv;
extern GLClearNamedFramebufferfi glClearNamedFramebufferfi;
extern GLBlitNamedFramebuffer glBlitNamedFramebuffer;
extern GLGetNamedFramebufferParameteriv glGetNamedFramebufferParameteriv;
extern GLGetNamedFramebufferAttachmentParameteriv glGetNamedFramebufferAttachmentParameteriv;
extern GLCreateRenderbuffers glCreateRenderbuffers;
extern GLNamedRenderbufferStorage glNamedRenderbufferStorage;
extern GLNamedRenderbufferStorageMultisample glNamedRenderbufferStorageMultisample;
extern GLGetNamedRenderbufferParameteriv glGetNamedRenderbufferParameteriv;
extern GLCreateTextures glCreateTextures;
extern GLTextureBuffer glTextureBuffer;
extern GLTextureBufferRange glTextureBufferRange;
extern GLTextureStorage1D glTextureStorage1D;
extern GLTextureStorage2D glTextureStorage2D;
extern GLTextureStorage3D glTextureStorage3D;
extern GLTextureStorage2DMultisample glTextureStorage2DMultisample;
extern GLTextureStorage3DMultisample glTextureStorage3DMultisample;
extern GLTextureSubImage1D glTextureSubImage1D;
extern GLTextureSubImage2D glTextureSubImage2D;
extern GLTextureSubImage3D glTextureSubImage3D;
extern GLCompressedTextureSubImage1D glCompressedTextureSubImage1D;
extern GLCompressedTextureSubImage2D glCompressedTextureSubImage2D;
extern GLCompressedTextureSubImage3D glCompressedTextureSubImage3D;
extern GLCopyTextureSubImage1D glCopyTextureSubImage1D;
extern GLCopyTextureSubImage2D glCopyTextureSubImage2D;
extern GLCopyTextureSubImage3D glCopyTextureSubImage3D;
extern GLTextureParameterf glTextureParameterf;
extern GLTextureParameterfv glTextureParameterfv;
extern GLTextureParameteri glTextureParameteri;
extern GLTextureParameterIiv glTextureParameterIiv;
extern GLTextureParameterIuiv glTextureParameterIuiv;
extern GLTextureParameteriv glTextureParameteriv;
extern GLGenerateTextureMipmap glGenerateTextureMipmap;
extern GLBindTextureUnit glBindTextureUnit;
extern GLGetTextureImage glGetTextureImage;
extern GLGetCompressedTextureImage glGetCompressedTextureImage;
extern GLGetTextureLevelParameterfv glGetTextureLevelParameterfv;
extern GLGetTextureLevelParameteriv glGetTextureLevelParameteriv;
extern GLGetTextureParameterfv glGetTextureParameterfv;
extern GLGetTextureParameterIiv glGetTextureParameterIiv;
extern GLGetTextureParameterIuiv glGetTextureParameterIuiv;
extern GLGetTextureParameteriv glGetTextureParameteriv;
extern GLCreateVertexArrays glCreateVertexArrays;
extern GLDisableVertexArrayAttrib glDisableVertexArrayAttrib;
extern GLEnableVertexArrayAttrib glEnableVertexArrayAttrib;
extern GLVertexArrayElementBuffer glVertexArrayElementBuffer;
extern GLVertexArrayVertexBuffer glVertexArrayVertexBuffer;
extern GLVertexArrayVertexBuffers glVertexArrayVertexBuffers;
extern GLVertexArrayAttribBinding glVertexArrayAttribBinding;
extern GLVertexArrayAttribFormat glVertexArrayAttribFormat;
extern GLVertexArrayAttribIFormat glVertexArrayAttribIFormat;
extern GLVertexArrayAttribLFormat glVertexArrayAttribLFormat;
extern GLVertexArrayBindingDivisor glVertexArrayBindingDivisor;
extern GLGetVertexArrayiv glGetVertexArrayiv;
extern GLGetVertexArrayIndexediv glGetVertexArrayIndexediv;
extern GLGetVertexArrayIndexed64iv glGetVertexArrayIndexed64iv;
extern GLCreateSamplers glCreateSamplers;
extern GLCreateProgramPipelines glCreateProgramPipelines;
extern GLCreateQueries glCreateQueries;
extern GLGetQueryBufferObjecti64v glGetQueryBufferObjecti64v;
extern GLGetQueryBufferObjectiv glGetQueryBufferObjectiv;
extern GLGetQueryBufferObjectui64v glGetQueryBufferObjectui64v;
extern GLGetQueryBufferObjectuiv glGetQueryBufferObjectuiv;
extern GLMemoryBarrierByRegion glMemoryBarrierByRegion;
extern GLGetTextureSubImage glGetTextureSubImage;
extern GLGetCompressedTextureSubImage glGetCompressedTextureSubImage;
extern GLGetnCompressedTexImage glGetnCompressedTexImage;
extern GLGetnTexImage glGetnTexImage;
extern GLGetnUniformdv glGetnUniformdv;
extern GLGetnUniformfv glGetnUniformfv;
extern GLGetnUniformiv glGetnUniformiv;
extern GLGetnUniformuiv glGetnUniformuiv;
extern GLReadnPixels glReadnPixels;
extern GLGetnMapdv glGetnMapdv;
extern GLGetnMapfv glGetnMapfv;
extern GLGetnMapiv glGetnMapiv;
extern GLGetnPixelMapfv glGetnPixelMapfv;
extern GLGetnPixelMapuiv glGetnPixelMapuiv;
extern GLGetnPixelMapusv glGetnPixelMapusv;
extern GLGetnPolygonStipple glGetnPolygonStipple;
extern GLGetnColorTable glGetnColorTable;
extern GLGetnConvolutionFilter glGetnConvolutionFilter;
extern GLGetnSeparableFilter glGetnSeparableFilter;
extern GLGetnHistogram glGetnHistogram;
extern GLGetnMinmax glGetnMinmax;
extern GLTextureBarrier glTextureBarrier;
extern GLSpecializeShader glSpecializeShader;
extern GLMultiDrawArraysIndirectCount glMultiDrawArraysIndirectCount;
extern GLMultiDrawElementsIndirectCount glMultiDrawElementsIndirectCount;
extern GLPolygonOffsetClamp glPolygonOffsetClamp;
extern GLBlendBarrier glBlendBarrier;
extern GLPrimitiveBoundingBox glPrimitiveBoundingBox;

GLContext* glCreateContext(GLContextOptions const&);
void glDestroyContext(GLContext*);
void glMakeCurrent(GLContext*);
void glSwapBuffers(GLContext*);
void* glLoadFunc(char const*);
bool glLoaded();
void glLoad();